[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "https://orangeseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.orangeseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://yellowseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.yellowseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://greenseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.greenseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://blueseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.blueseat.co.nz/*"
  to = "https://theseats.co.nz/:splat"
  status = 301
  force = true